# Generated by Django 4.2.21 on 2025-05-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interviewquestion',
            table='question',
        ),
    ]
