# Generated by Django 4.2.21 on 2025-05-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_interviewquestion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interviewquestion',
            table=None,
        ),
    ]
